# Generated by Django 4.1.7 on 2023-04-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="d",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(default="unknown", max_length=120)),
                ("email", models.EmailField(default="unknown mail", max_length=254)),
                ("amount", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Donate_class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(default="unknown", max_length=120)),
                ("email", models.EmailField(default="unknown mail", max_length=254)),
                ("amount", models.IntegerField(default=0)),
                ("leave_a_comment", models.CharField(default="empty", max_length=1000)),
                ("name_on_card", models.CharField(max_length=120)),
                ("card_number", models.IntegerField()),
                ("expire_month", models.IntegerField()),
                ("expire_year", models.IntegerField()),
                ("cvv", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ExamGPTModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_name", models.CharField(max_length=100)),
                ("grade", models.CharField(max_length=12)),
                ("subject", models.CharField(max_length=50)),
                ("topic_name", models.CharField(max_length=100)),
                ("teacher_name", models.CharField(max_length=60)),
                (
                    "topic_language",
                    models.CharField(
                        choices=[("English", "english"), ("Arabic", "arabic")],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrackTeacherModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("oldfile", models.FileField(upload_to="track_teachers/")),
                ("newfile", models.FileField(upload_to="track_teachers/")),
            ],
        ),
    ]
