# Generated by Django 4.1.7 on 2023-04-29 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="d",
            new_name="Donate",
        ),
        migrations.DeleteModel(
            name="Donate_class",
        ),
    ]
