# Generated by Django 4.1.7 on 2023-05-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_rename_d_donate_delete_donate_class"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name_contact_us", models.CharField(max_length=120)),
                ("last_name_contact_us", models.CharField(max_length=120)),
                ("email_contact_us", models.EmailField(max_length=254)),
                ("number_contact_us", models.IntegerField()),
                ("inquiry_contact_us", models.CharField(max_length=5000)),
            ],
        ),
    ]
