# Generated by Django 4.1.7 on 2023-05-15 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_contactus"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonPlanGPT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_name", models.CharField(max_length=100)),
                ("grade", models.CharField(max_length=12)),
                ("subject", models.CharField(max_length=50)),
                ("lesson_name", models.CharField(max_length=500)),
                ("teacher_name", models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name="examgptmodel",
            name="topic_name",
            field=models.CharField(max_length=300),
        ),
    ]
