# Generated by Django 4.1.7 on 2023-05-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_rename_lessonplangpt_lessonplangptmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamGPTWhisperModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lesson_name", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="LessonGPTWhisperModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lesson_name", models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name="examgptmodel",
            old_name="topic_name",
            new_name="lesson_name",
        ),
    ]
